services:
  app:
    build: ./app
    container_name: web-app
    hostname: web-app
    volumes: ["./app/src:/appcode"]
    ports:
      - 8501:8501
    networks:
      - app-network
    depends_on:
      - api

  api:
    build: ./api
    container_name: web-api
    hostname: web-api
    volumes: ["./api:/apicode"]
    ports:
      - 4000:4000
    networks:
      - app-network
    depends_on:
      - db

  db:
    env_file:
      - ./api/.env
    image: mysql:8.0.33
    container_name: mysql_db
    hostname: db
    volumes:
      - ./database-files/tummy-base.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3200:3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
